init-scratch:
  only: 
    - master
  script:
    - conda deactivate
    - conda env create -f environment.yml -n pysyintegration python
    - conda init bash
    - conda activate pysyintegration
    - pip install -r requirements.txt

unittests-scratch:
  only:
    - master
  script:
    - conda activate pysyintegration
    - python -m pytest --junit-xml=pytest_unit.xml

post-scratch:
  only: 
    - master
  script:
    - conda remove --yes -n pysyintegration --all
    
unittests:
  except:
    - master
  tags:
    - default
  script:
    - pytest