stages:
  - build
  - test
  - cleanup

test:
  stage: test
  script:
    - source ~/.bashrc
    - conda activate pysyintegration
    - pip install --upgrade --no-deps -v -e .
    - python -m pytest
  except:
    - master

build-full:
  stage: build
  script:
    - conda env create -f environment.yml -n pysyintegration_m python --force
    - source ~/.bashrc
    - conda activate pysyintegration_m
  only:
    - master

test-full:
  stage: test
  script:
    - source ~/.bashrc
    - conda activate pysyintegration_m
    - pip install --upgrade --no-deps -v -e .
    - python -m pytest -c tests/full_run.ini
  only:
    - master

cleanup:
  stage: cleanup
  script:
    - conda remove --yes -n pysyintegration_m --all
  when: always
  only:
    - master

pylint:
  stage: test
  before_script:
    - pip install pylint pylint-exit anybadge
  script:
    - mkdir ./pylint
    - pylint --output-format=text syconn | tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/
    expire_in: 2 yrs
  allow_failure: true
  only:
    - master