stages:
  - build
  - test
  - cleanup

test:
  stage: test
  script:
    - source ~/.bashrc
    - conda activate pysyintegration
    - pip install --upgrade -e .
    - pytest --ignore=tests/test_run.py
  except:
    - master

test-full:
  stage: test
  script:
    - source ~/.bashrc
    - conda activate pysyintegration_m
    - pytest
  only:
    - master
  tags:
    - master

build:
  stage: build
  # TODO: use conda environment for test stage
  script:
    - echo "Installing SyConn"
    - conda env create -f environment.yml -n pysyintegration_m python
    - source ~/.bashrc
    - conda activate pysyintegration_m
    - pip install --no-deps -v .
  only:
    - master
  tags:
    - master

cleanup:
  stage: cleanup
  script:
    - conda remove --yes -n pysyintegration_m --all
  when: always
  only:
    - master
  tags:
    - master