build:
  script:
    - conda env create -f environment.yml -n pysyintegration python
    - conda init 
    - conda activate pysyintegration
    - pip install -r requirements.txt

test-unit:
  script:
    - conda activate pysyintegration
    - python -m pytest --junit-xml=pytest_unit.xml

post:
  script:
    - conda remove --yes -n pysyintegration --all