stages:
  - build
  - test
  - cleanup

test:
  stage: test
  script:
    - pytest --ignore=tests/test_run.py
  except:
    - master

test-full:
  stage: test
  script:
    - pytest
  only:
    - master
  tags:
    - master

build:
  stage: build
  # TODO: use conda environment for test stage
  script:
    - echo "Installing SyConn"
    - conda env create -f environment.yml -n pysyintegration python
    - source activate pysyintegration
    - pip install --no-deps -v .
  only:
    - master
  tags:
    - master

cleanup:
  stage: cleanup
  script:
    - conda remove --yes -n pysyintegration --all
  only:
    - master
  tags:
    - master