language: python
addons:
  apt:
    packages:
    - libsnappy-dev
install:
  - pip install python-snappy
script:
  - true

build:
  image: latest

requirements_file: requirements.txt

python:
  pip_install: false
  version: 3.5

#conda:
#  file: environment.yml

formats: []
