# Dependencies marked with "(optional)" are not required for core functionality
# and can be commented out if there are conflicts.

name: pysy
channels:
  - pytorch
  - conda-forge
  - defaults
  - menpo
dependencies:
  # From -c pytorch
  - pytorch =1.1  # (version depends on elektronn3 revision)
  - torchvision

  # From conda-forge and defaults
  - python >=3.7  # (3.6 should also work)
  - pip
  - vigra
  - freeglut
  - pyopengl
  - python-snappy
  - ipython
  - h5py
  - matplotlib
  - tqdm
  - scipy
  - networkx <= 2.3  # AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'
  - m2r
  - lz4
  - flask
  - fasteners
  - numpy
  - coloredlogs
  - termcolor
  - scikit-learn =0.21
  - scikit-image
  - pyopengl
  - opencv
  - numba
  - openmesh-python
  - prompt_toolkit
  - vtki
  - dill
  - joblib
  - seaborn
  - pyyaml
  - cython
  - colorlog
  - plyfile
  - zmesh
  - tensorboard

  # From -c menpo
  - osmesa

  # For tests (optional):
  - pytest
  - pytest-runner
  - pytest-cov
  - pytest-forked

  # For docs (optional):
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints

  # Required dependencies that are not yet available via conda:
  - pip:
    # Pre-release packages
    - git+https://github.com/ELEKTRONN/elektronn3.git@phil#egg=elektronn3
    - git+https://github.com/knossos-project/knossos_utils@dev#egg=knossos_utils

    - adabound # TODO: Remove when models no longer depend on this code
